direction: down

Vault: {
  label: Vault
  shape: image
  icon: https://www.svgrepo.com/download/448679/vault.svg
}

AWSSM: {
  label: AWS Secrets Manager
  shape: image
  icon: https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Secrets-Manager.svg
  style: {
    opacity: 0.4
  }
}

GCPSM: {
  label: GCP Secret Manager
  shape: image
  icon: https://www.svgrepo.com/download/375492/secret-manager.svg
  style: {
    opacity: 0.4
  }
}

AzureKeyVault: {
  label: Azure Key Vault
  shape: image
  icon: https://icons.terrastruct.com/azure%2FSecurity%20Service%20Color%2FKey%20Vaults.svg
  style: {
    opacity: 0.4
  }
}

BVSecretSync: {
  label: Bank-Vaults Secret Sync
  shape: image
  icon: https://raw.githubusercontent.com/bank-vaults/bank-vaults.dev/main/assets/icons/logo.svg
}

Vault -> BVSecretSync
AWSSM -> BVSecretSync {
  style: {
    opacity: 0.4
  }
}
GCPSM -> BVSecretSync {
  style: {
    opacity: 0.4
  }
}
AzureKeyVault -> BVSecretSync {
  style: {
    opacity: 0.4
  }
}

ClusterA: {
  label: Cluster A
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  style: {
    opacity: 0.4
  }

  LocalA: Secret {
    style: {
      opacity: 0.4
    }
  }
  WorkloadA: Workload {
      style: {
        opacity: 0.4
      }
  }

  LocalA -> WorkloadA {
    style: {
      opacity: 0.4
    }
  }
}

ClusterB: {
  label: Cluster B
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  LocalB: {
    label: Local Vault
    shape: image
    width: 80
    icon: https://www.svgrepo.com/download/448679/vault.svg
  }
  WorkloadB: Workload

  LocalB -> WorkloadB
}

LocalC: {
    label: Tenant Environment
    shape: image
    width: 80
    icon: https://www.svgrepo.com/download/375492/secret-manager.svg
    style: {
      opacity: 0.4
    }
}

ClusterC: {
  label: Cluster C
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  style: {
    opacity: 0.4
  }

  WorkloadC: Workload {
      style: {
        opacity: 0.4
      }
  }
}

LocalC -> ClusterC.WorkloadC

BVSecretSync -> ClusterB.LocalB: Sync
BVSecretSync -> ClusterA.LocalA: Sync {
  style: {
    opacity: 0.4
  }
}
BVSecretSync -> LocalC: Sync {
  style: {
    opacity: 0.4
  }
}
